voornaam = input("Wat is je voornaam? ")
achternaam = input("Wat is je achternaam? ")
leeftijd = int(input("Wat is je leeftijd? "))
woonplaats = input("Waar woon je? ")
hobby1 = input("Wat is je eerste hobby? ")
hobby2 = input("Wat is je tweede hobby? ")
hobby3 = input("Wat is je derde hobby? ")

print("-----------------------")
print("PERSOONLIJK PROFIEL")
print("-----------------------")
print("Naam: " + voornaam + " " + achternaam)
print("Leeftijd: " + str(leeftijd) + " jaar")
print("Hobby's: ")
print("1. " + hobby1)
print("2. " + hobby2)
print("3. " + hobby3)
print("Samenvatting: Ik ben " + voornaam + ", " + str(leeftijd) + " jaar oud, woon in " + woonplaats + " en hoe van " + hobby1 + ", " + hobby2 + " en " + hobby3 + ".")
print("-----------------------")